name: CI Pipeline
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  Empacotamento:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
 
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
 
      - name: Install dependencies
        run: npm install
 
  Testes:
    runs-on: ubuntu-latest
    needs: Empacotamento
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
 
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
 
      - name: Install dependencies
        run: npm install
 
      - name: Fix Jest permissions
        run: chmod +x ./node_modules/.bin/jest
 
      - name: Test
        run: npm test
        env:
          JEST_JUNIT_OUTPUT_DIR: ./test-results
 
      - name: Upload Jest Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-report
          path: test-results/junit.xml
  Notificacao:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v4
      - name: Notification
        run: sh scripts/shell.sh